title: Dawit Hiluf Hailu 
theme: jekyll-theme-minimal
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
